### ISSUE TITLE
Regarding parameters

### ISSUE THREAD

**Issue by harithzulfaizal** [sfc-gh-bhess/st_oauth#1]
Just wondering if these parameters are necessary since my provider doesn't seem to have these,

> audience - the audience as configured in the OAuth provider
identity_field_in_token - which field in the returned token that contains the identity (usually it is sub or upn). This is the field that will be returned from the st_oauth() call.

**Comment by sfc-gh-bhess** [comment]
Those are not necessarily required. I have made them optional now.
