### ISSUE TITLE
Please replace st.experimental_get_query_params with st.query_params

### ISSUE THREAD

**Issue by esnible** [sfc-gh-bhess/st_oauth#11]
With recent versions of Streamlit (`streamlit==1.30.0`), the login shows

```
Please replace st.experimental_get_query_params with st.query_params.

st.experimental_get_query_params will be removed after 2024-04-11.

Refer to our [docs page](https://docs.streamlit.io/library/api-reference/utilities/st.query_params) for more information.

Please replace st.experimental_get_query_params with st.query_params.

st.experimental_get_query_params will be removed after 2024-04-11.

Refer to our [docs page](https://docs.streamlit.io/library/api-reference/utilities/st.query_params) for more information.
```

**Comment by Olney1** [comment]
I am getting this too. Very repetitive and the docs page is not helping, no way to suppress this. This is how I am currently using it which works - but no longer works using the updated `st.query_params`

`# Check if the page was loaded with query parameters indicating a successful payment
query_params = st.experimental_get_query_params()

if 'payment_status' in query_params and query_params['payment_status'][0] == 'success':
    lead_name = query_params.get('lead_name', [None])[0]
    payment_reference = query_params.get('payment_reference', [None])[0]

    if lead_name and payment_reference:
        valid_reference = payment_reference is not None and payment_reference != ""
        if valid_reference:
            delete_lead_row(lead_name, payment_reference)
        else:
            st.error("Invalid payment reference provided.")
    else:
        st.error("Invalid parameters provided.")`

**Comment by sfc-gh-bhess** [comment]
Updated with query_params.
