### ISSUE TITLE
snowauth_session() 

### ISSUE THREAD

**Issue by carolinablue453** [sfc-gh-bhess/st_oauth#5]
I am currently supporting a multipage app and need to validate session state prior to loading each page.  I'm not seeing any function in the library called snowauth_session() to handle this validation.

**Comment by carolinablue453** [comment]
I ended up finding that if I use st_ouath() at the top of each page instead of snowauth_session(), the same goal is achieved.  I saw your snowauth repo and noticed the function is pretty much doing the same thing.  Only suggestion would be to update the README.md for this repo

**Comment by sfc-gh-bhess** [comment]
I see the error in the README. I updated it. Thanks!
